apiVersion: v1
kind: Service
metadata:
  name: debug
  labels:
    app: debug
spec:
  ports:
  - port: 8080
    name: debug
  selector:
    app: debug
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: debug
spec:
  serviceName: debug
  replicas: 1
  template:
    metadata:
      labels:
        app: debug
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: debug
        image: gcr.io/watchly-service/debug:v4
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: debug
        volumeMounts:
        - name: data-volume
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data-volume
      annotations:
        volume.beta.kubernetes.io/storage-class: "slow"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Gi
